src/layouts/Header.jsx, src/layouts/Sidebar.jsx
feat: add notification count for ATS health check and manage notification read state
=> notification counter

src/components/AnalysisComponents/ApplicationReceived.jsx, src/components/AnalysisComponents/SourceOfApplication.jsx
Add application trend and source data fetching to analysis components
=> Integraded some endpoint of analytics page

src/components/Modals/ATSHeathcheck.jsx, src/pages/Listings.jsx
Add notification visibility control to ATS Healthcheck modal
🚀 LETSSS GOOOOOO!!!!
=> Added a function to close the notif if an applicant is clicked

src/assets/Loader.jsx
Enhance Loader component with customizable options for spinner type, size, color, and fullscreen display
=> Improve the loading Component

src/components/Applicant/ApplicantDetails.jsx, src/components/Applicant/ApplicantDiscussionPage.jsx, src/index.css, src/pages/ApplicantDetailsPage.jsx
=> Modified Ui for Applicant Details

package.json, src/layouts/ApplicantList.jsx, src/utils/ExportToPdf.jsx, src/utils/exportToPdf.js
implement a pdf export feature
=> feat: add pdf export

src/components/ApplicantTable.jsx, src/layouts/StatusCounter.jsx
=> added stage filtering

src/assets/Toast.jsx, src/components/Applicant/ApplicantDetails.jsx, src/components/ApplicantTable.jsx
Change user_id to be fetched from Zustand instead of JwtDecode. Also, refactor the ApplicantDetails function to include user_id in the Axios request.
=> Applicant Details status change fix

src/components/ApplicantTable.jsx
fixed applicant list not sorted
=> default desc on date applied

src/layouts/ApplicantList.jsx, src/utils/applicantDataUtils.jsx
=> added search applicant by name

src/components/Applicant/ApplicantSendMailPage.jsx
refactor: update attachment handling to support multiple files
=> Send Email UI

src/context/applicantFilterStore.jsx, src/layouts/ApplicantList.jsx, src/layouts/StatusCounter.jsx, src/utils/applicantDataUtils.jsx
=> added applicant search with position

src/layouts/ApplicantList.jsx, src/layouts/StatusCounter.jsx, src/utils/applicantDataUtils.jsx
=> added search applicant with status

src/components/Applicant/ApplicantDiscussionPage.jsx, src/components/DiscussionBox.jsx, src/components/InterviewNotes.jsx, src/pages/ApplicantDetailsPage.jsx
Add Discussion and Add Interview /  Note Functionality.
=> Discussion and Add Interview /  Note Functionality

src/components/ApplicantTable.jsx, src/context/applicantFilterStore.jsx, src/layouts/ApplicantList.jsx, src/layouts/StatusCounter.jsx, src/utils/applicantDataUtils.jsx
added year and month filtering for applicants
=> Search applicant date

src/components/Applicant/ApplicantDetails.jsx, src/components/Applicant/ApplicantSendMailPage.jsx, src/components/ApplicantTable.jsx, src/pages/ApplicantDetailsPage.jsx
Fix email functionality by passing the correct user_id and applicant_id to the email component.
=> Fix email functionality 

src/components/Applicant/ApplicantSendMailPage.jsx
fix the issue in uploading attatcment when sending email by adding the files individually
=> PR: Fix attachment upload in email

src/components/ApplicantTable.jsx, src/layouts/StatusCounter.jsx, src/utils/toastManager.js
=> Fixed status counter not reverting after undoing status change

src/components/ApplicantTable.jsx
=> Fixed loading applicant

src/context/applicantFilterStore.jsx, src/hooks/useStages.jsx, src/layouts/ApplicantList.jsx, src/layouts/StatusCounter.jsx
=> Fix: Fixed stage filtering not updating the status filter

src/components/ApplicantTable.jsx, src/layouts/ApplicantList.jsx, src/utils/applicantDataUtils.jsx, src/utils/applicantListUtils.jsx
=> Bug fixes2

src/components/ApplicantTable.jsx, src/utils/applicantDataUtils.jsx
Co-authored-by: DarcMattz <johnvirgilcarvajal@gmail.com>
=> Listing fix

src/components/SmtpConfig..jsx, src/pages/Configurations.jsx, src/pages/Listings.jsx
add SMTP configuration component and update configurations page
=> feat: add smpt config

src/components/ApplicantTable.jsx, src/components/DiscussionBox.jsx, src/components/InterviewNotes.jsx, src/pages/AnalysisPage.jsx
fixed discussion and interview
=> fixed discussion and interview note

src/components/Applicant/ApplicantDetails.jsx, src/components/JobsTable.jsx, src/context/jobListingStore.jsx, src/utils/jobListing.jsx
=> Job listing

src/components/IndustriesTable.jsx, src/context/industriesStore.jsx, src/utils/industriesUtils.jsx
=> fetched industries in database

src/components/SetupsTable.jsx, src/context/setupStore.jsx, src/utils/setupUtils.jsx
=> fetched setups

src/components/IndustriesTable.jsx, src/components/SetupsTable.jsx, src/layouts/JobList.jsx, src/utils/jobListing.jsx
=> Search jobs

src/context/jobListingStore.jsx, src/layouts/JobList.jsx, src/pages/Jobs.jsx
show industries modal when counter is clicked
=> show industries modal when industries counter clicked

src/components/JobsTable.jsx, src/pages/Jobs.jsx, src/utils/jobListing.jsx
=> added filter functionality for open and close jobs

src/components/IndustriesTable.jsx, src/components/JobsTable.jsx, src/components/SetupsTable.jsx, src/pages/Jobs.jsx, src/utils/jobListing.jsx
=> added job update functionality

src/components/JobsTable.jsx, src/layouts/JobList.jsx, src/utils/jobListing.jsx
=> added add job functionality

src/components/JobsTable.jsx, src/components/Modals/AddIndustryModal.jsx, src/components/Modals/AddSetupModal.jsx, src/context/jobListingStore.jsx, src/pages/Jobs.jsx, src/utils/industriesUtils.jsx, src/utils/setupUtils.jsx
=> added functionality to add industry and setup

src/pages/LoginPage.jsx, src/pages/ResetPassword.jsx
and improve the ui for ResetPasswordPage
=> style: Improve styling of the "Forgot password?" link on LoginPage

src/pages/AddApplicantForm.jsx
=> updated the duplicate on email and phone

src/components/Applicant/ApplicantDiscussionPage.jsx, src/components/DiscussionBox.jsx
include necessary id's for slack integration
=> PR: Slack integration

src/pages/AnalysisPage.jsx
=> Timetohire

src/components/Applicant/ApplicantDiscussionPage.jsx, src/components/Gdrive.jsx, src/components/JobsTable.jsx, src/components/Modals/PendingApplicantConfirmationModal.jsx, src/components/SmtpConfig..jsx, src/components/user-management/UserForm.jsx, src/layouts/JobList.jsx, src/pages/AddApplicantForm.jsx, src/pages/Dashboard.jsx, src/pages/LoginPage.jsx
=> Add loader new
